def byeScreen():
    print('      .      ')
    print('      :      ')
    print('\'.___/*\___.\'')
    print('  \* \ / */  ')
    print('   >--X--<   ')
    print('  /*_/ \_*\  ')
    print('.\'   \* /   \'.')
    print('      :      ')
    print('      \'      ')
    print('\n')
    print('Merry Christmas!' + '\n' + '\n')


def welcomeScreen(name):
    print('\n' + '   *      *   ')
    print('   _\/  \/_   ')
    print('    _\/\/_    ')
    print('_\_\_\/\/_/_/_')
    print(' / /_/\/\_\ \ ')
    print('    _/\/\_    ')
    print('    /\  /\    ')
    print('   *      *   ')
    print('Season\'s Greetings!' + '\n' + '\n')
    print('Welcome to ' + name + '\n' + '\n')
